//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BM_Medical_Resource {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BM_Medical_Resource.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add to cart benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AddCart {
            get {
                return ResourceManager.GetString("AddCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Category benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AddCategory {
            get {
                return ResourceManager.GetString("AddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Product benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AddProduct {
            get {
                return ResourceManager.GetString("AddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add User benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BM-Medical Admin Page benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AdminPage {
            get {
                return ResourceManager.GetString("AdminPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Admin Panel benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AdminPanel {
            get {
                return ResourceManager.GetString("AdminPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adress benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Adress {
            get {
                return ResourceManager.GetString("Adress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Black benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blue benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BM-Medical benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BM_Medical {
            get {
                return ResourceManager.GetString("BM_Medical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cart benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Cart {
            get {
                return ResourceManager.GetString("Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Categories benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Category benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Category Id benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CategoryId {
            get {
                return ResourceManager.GetString("CategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Category Information benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CategoryInformation {
            get {
                return ResourceManager.GetString("CategoryInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Category Name benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   City benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Colors benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Colors {
            get {
                return ResourceManager.GetString("Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Combination x 1 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Combination {
            get {
                return ResourceManager.GetString("Combination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Complete Order benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CompleteOrder {
            get {
                return ResourceManager.GetString("CompleteOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Contact benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Contact Us benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Continue to Shopping benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ContinueShopping {
            get {
                return ResourceManager.GetString("ContinueShopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   |  Created by Berkay &amp; Metin benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CopyRight {
            get {
                return ResourceManager.GetString("CopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Coronavirus benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Coronavirus {
            get {
                return ResourceManager.GetString("Coronavirus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dashboard benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Description benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Development Mode benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Development_Mode {
            get {
                return ResourceManager.GetString("Development_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disinfectant benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Disinfectant {
            get {
                return ResourceManager.GetString("Disinfectant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disinfectants benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Disinfectants {
            get {
                return ResourceManager.GetString("Disinfectants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error occurred while processing your request. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Error_Detail {
            get {
                return ResourceManager.GetString("Error_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   hellocolorlib@gmail.com benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExampleMail {
            get {
                return ResourceManager.GetString("ExampleMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   bm_medical@gmail.com benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExampleMail_2 {
            get {
                return ResourceManager.GetString("ExampleMail_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0532 777 11 22 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExamplePhoneNumber {
            get {
                return ResourceManager.GetString("ExamplePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Logout benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Filtre benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Finishing to Shopping benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FinishShopping {
            get {
                return ResourceManager.GetString("FinishShopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Give Order benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string GiveOrder {
            get {
                return ResourceManager.GetString("GiveOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Glove benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Glove {
            get {
                return ResourceManager.GetString("Glove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gloves benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Gloves {
            get {
                return ResourceManager.GetString("Gloves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Go to cart benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string GoToCart {
            get {
                return ResourceManager.GetString("GoToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yeşil benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hello benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Home Page benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Information benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Detail of Invoice benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string InvoiceDetail {
            get {
                return ResourceManager.GetString("InvoiceDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sign in benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        /// benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LoremIpsum {
            get {
                return ResourceManager.GetString("LoremIpsum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E-Mail benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Main Page benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MainPage {
            get {
                return ResourceManager.GetString("MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Masks benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Masks {
            get {
                return ResourceManager.GetString("Masks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   More benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click for detailed information benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MoreInformation {
            get {
                return ResourceManager.GetString("MoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   My Account benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number of Products on the Site benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string NumberOfProducts {
            get {
                return ResourceManager.GetString("NumberOfProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number of Users Registered on the Site benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string NumberOfUsers {
            get {
                return ResourceManager.GetString("NumberOfUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string One {
            get {
                return ResourceManager.GetString("One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   According to the data of the World Health Organization, as of November 12, 2020, a total of 212 vaccine studies for Covid-19 continue in dozens of countries, including Turkey. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Paragraph_1 {
            get {
                return ResourceManager.GetString("Paragraph_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Although more than one type of COVID-19 vaccine can be administered in our country during the process, inactive COVID-19 vaccine (Sinovac) and mRNA COVID-19 vaccine (Biontech) are currently being administered. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Paragraph_2 {
            get {
                return ResourceManager.GetString("Paragraph_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Symptoms of the new coronavirus infection include fever, cough, shortness of breath and difficulty breathing. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Paragraph_3 {
            get {
                return ResourceManager.GetString("Paragraph_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Phone Number benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Picture benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pure Pineapple benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Pineapple {
            get {
                return ResourceManager.GetString("Pineapple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   60 ₺ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   $60.00 x 1 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Price_2 {
            get {
                return ResourceManager.GetString("Price_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   $64.00 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Price_3 {
            get {
                return ResourceManager.GetString("Price_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   $35.00 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Price_4 {
            get {
                return ResourceManager.GetString("Price_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   $44.00 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Price_5 {
            get {
                return ResourceManager.GetString("Price_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   $34.00 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Price_6 {
            get {
                return ResourceManager.GetString("Price_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kabino Bedside Table benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Product Detail benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ProductDetail {
            get {
                return ResourceManager.GetString("ProductDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Product Explanation benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ProductExplanation {
            get {
                return ResourceManager.GetString("ProductExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Product Id benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ProductId {
            get {
                return ResourceManager.GetString("ProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Product Information benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ProductInformation {
            get {
                return ResourceManager.GetString("ProductInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Product Name benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Price (₺) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ProductPrice {
            get {
                return ResourceManager.GetString("ProductPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Products benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stock benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ProductStock {
            get {
                return ResourceManager.GetString("ProductStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Red benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Register benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Request ID: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Request_Id {
            get {
                return ResourceManager.GetString("Request_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Role benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sakarya University Esentepe Campus benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Sakarya {
            get {
                return ResourceManager.GetString("Sakarya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Category benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SelectCategory {
            get {
                return ResourceManager.GetString("SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Converse Shoes benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Shoes {
            get {
                return ResourceManager.GetString("Shoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shop benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Shop {
            get {
                return ResourceManager.GetString("Shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shopping benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Shopping {
            get {
                return ResourceManager.GetString("Shopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sign up benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recently Sold Items benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SoldProduct {
            get {
                return ResourceManager.GetString("SoldProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Surname benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Syndrome benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Syndrome {
            get {
                return ResourceManager.GetString("Syndrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   3 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Three {
            get {
                return ResourceManager.GetString("Three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total Income benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TotalIncome {
            get {
                return ResourceManager.GetString("TotalIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total Price benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Turkish benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Turkish {
            get {
                return ResourceManager.GetString("Turkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User Adress benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string UserAdress {
            get {
                return ResourceManager.GetString("UserAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   City ​​where the user lives benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string UserCity {
            get {
                return ResourceManager.GetString("UserCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User Information benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string UserInformation {
            get {
                return ResourceManager.GetString("UserInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User Mail benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string UserMail {
            get {
                return ResourceManager.GetString("UserMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User Name benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Users benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User Surname benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string UserSurname {
            get {
                return ResourceManager.GetString("UserSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   News about vaccination benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string VacationNews {
            get {
                return ResourceManager.GetString("VacationNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Virus Studies benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string VirusStudies {
            get {
                return ResourceManager.GetString("VirusStudies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Visors benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Visors {
            get {
                return ResourceManager.GetString("Visors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2 Layer Windbreaker benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Windbreaker {
            get {
                return ResourceManager.GetString("Windbreaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yellow benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your Orders benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string YourOrders {
            get {
                return ResourceManager.GetString("YourOrders", resourceCulture);
            }
        }
    }
}
